INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Sea Pearl Beach Resort & Spa',
'Jaliapalong, Inani, Ukhia 4750',
'package-1.jpg',
'TP0002',
3,
12500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Cox's Bazar",
"",
15,
curdate(), 'System', curdate(), 'System');

INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Saint Place',
'1A Rhine Road, Maho St Martin / St Maarten',
'package-2.jpg',
'TP0001',
3,
9500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Saint Martin",
"",
15,
curdate(), 'System', curdate(), 'System');
INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Nilgiri Resort',
'7/2, Nilgiri / Bandarban',
'package-3.jpg',
'TP0003',
3,
7500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Bandarban",
"",
15,
curdate(), 'System', curdate(), 'System');
INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Rangamati Cottage',
' 6 no hazli road, Rangamati Sadar,Rangamati',
'package-4.jpg',
'TP0004',
3,
6500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Rangamati",
"",
15,
curdate(), 'System', curdate(), 'System');
INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Stone Bay Hotel',
'143 Jaflong Bazar / Sylhet',
'package-5.jpg',
'TP0005',
3,
4500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Jaflong",
"",
15,
curdate(), 'System', curdate(), 'System');
INSERT INTO `tms`.`packages`
(
`HotelName`,
`HodelAddress`,
`HotelImages`,
`Code`,
`Duration`,
`AdultPerPersonCost`,
`ChildPerPersonCost`,
`Facilities`,
`Discount`,
`Type`,
`Location`,
`LocationImages`,
`TotalSlot`,
`CreatedAt`,
`CreatedBy`,
`ModifiedAt`,
`ModifiedBy`)
VALUES
(
'Sajek Resort',
'Sajek Hill / Sajek',
'package-6.jpg',
'TP0006',
3,
8500,
0,
"The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please",
0,
'Honeymoon,Vacation',
"Sajek",
"",
15,
curdate(), 'System', curdate(), 'System');
